#!/usr/bin/env python3
"""
build.py — FinReport License Generator Builder
===============================================
Generates 'license-generator-offline.html' dengan semua file app
ter-embed sebagai base64. File output bisa dibuka langsung di browser
tanpa perlu server (file:// protocol).

Jalankan ulang setiap kali ada update pada folder app/.
"""

import os, base64, json, webbrowser, sys, time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
APP_DIR    = os.path.join(SCRIPT_DIR, 'app')
SRC        = os.path.join(SCRIPT_DIR, 'license-generator.html')
OUT        = os.path.join(SCRIPT_DIR, 'license-generator-offline.html')

APP_FILES = [
    'index.html',
    'css/style.css',
    'js/app.js',
    'js/auth.js',
    'js/coa.js',
    'js/export.js',
    'js/journal.js',
    'js/license.js',
    'js/parser.js',
    'js/pos.js',
    'js/purchase.js',
    'js/sales.js',
    'js/storage.js',
    'js/reports.js',
    'js/users.js',
    'assets/logo.svg',
    'serve.py',
    'start.sh',
    'start.bat',
    'data/.gitkeep',
    'filestore/.gitkeep',
]

def build():
    print('FinReport License Generator — Build Tool')
    print('=' * 42)

    # 1. Baca & encode semua file app
    embedded = {}
    total_bytes = 0
    for f in APP_FILES:
        path = os.path.join(APP_DIR, f)
        if os.path.exists(path):
            with open(path, 'rb') as fp:
                raw = fp.read()
            embedded[f] = base64.b64encode(raw).decode('ascii')
            total_bytes += len(raw)
            print(f'  + {f} ({len(raw):,} bytes)')
        else:
            print(f'  ! SKIP (not found): {f}')

    print(f'\n  Total app files: {len(embedded)} ({total_bytes/1024:.0f} KB)')

    # 2. Baca source HTML
    with open(SRC, 'r', encoding='utf-8') as f:
        html = f.read()

    # 3. Inject _EMBEDDED_FILES sebelum 'const APP_FILES'
    #    Marker: baris 'const APP_FILES = ['
    inject = (
        '\n// [AUTO-GENERATED by build.py — DO NOT EDIT]\n'
        'const _EMBEDDED_FILES = ' + json.dumps(embedded) + ';\n\n'
    )
    if 'const APP_FILES = [' not in html:
        print('\nERROR: Marker "const APP_FILES = [" tidak ditemukan di source HTML.')
        sys.exit(1)

    html_out = html.replace('const APP_FILES = [', inject + 'const APP_FILES = [', 1)

    # 4. Tambahkan banner di title & topbar agar mudah dibedakan
    html_out = html_out.replace(
        '<title>FinReport — License Key Generator</title>',
        '<title>FinReport — License Generator (Offline)</title>'
    )
    html_out = html_out.replace(
        'FinReport <span>License Generator</span>',
        'FinReport <span>License Generator</span> <span style="background:#166534;color:#bbf7d0;font-size:11px;padding:2px 8px;border-radius:99px;margin-left:8px">OFFLINE</span>'
    )

    # 5. Tulis output
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(html_out)

    out_kb = os.path.getsize(OUT) // 1024
    print(f'\n✓ Output: license-generator-offline.html ({out_kb} KB)')
    print(f'✓ Selesai! File siap dibuka di browser.\n')
    return OUT


if __name__ == '__main__':
    try:
        out = build()
        if '--no-open' not in sys.argv:
            # Buka di browser default
            file_url = 'file://' + out.replace('\\', '/')
            webbrowser.open(file_url)
            print('✓ Membuka di browser...')
    except Exception as e:
        print(f'\nERROR: {e}')
        import traceback; traceback.print_exc()
        input('\nTekan Enter untuk keluar...')
        sys.exit(1)
